#Crear aplicativo que reciba 4 valores
#Sume los 2 primeros valores y reste los 2 ultimos
#Mostrar resultado

def valores():
  
  n1=int(input("Ingrese primer numero: "))
  n2=int(input("Ingrese primer numero: "))
  n3=int(input("Ingrese primer numero: "))
  n4=int(input("Ingrese primer numero: "))

  suma= n1+n2
  print("La suma de los valores es:,",suma)

  resta= n3-n4
  print("La esta de los valores es:" ,resta)
  
valores() 